GET http://localhost:3001/players

###

GET http://localhost:3001/player/2

###

POST http://localhost:3001/player
Content-Type: application/json

{
    "fname": "Joao",
    "lname": "Arezzo",
    "age":"23", 
    "country":"Uruguai",
    "position":"CAM",
    "club":"Gremio",
    "matches":"25",
    "scored":"12",
    "assist":"3"
}

###

PUT http://localhost:3001/player/edit/4
Content-Type: application/json

{
    "fname": "Pedro",
    "lname": "Arezzo",
    "age":"23", 
    "country":"Uruguai",
    "position":"CAM",
    "club":"Gremio",
    "matches":"25",
    "scored":"12",
    "assist":"5"
}

### 

DELETE http://localhost:3001/player/edit/3

