GET http://localhost:3001/players
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikxlb25hcmRvIiwidXNlcm5hbWUiOiJ0ZXN0ZSIsImVtYWlsIjoibGVlb25hcmRvbHV6QGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcEpBSnFKaVgwVFZOc09RRWlmbzR0dVBKenFjNFJxR3FYTDRyTGR6VFVWNnFtVjJJekFrNzIiLCJpYXQiOjE3MjI1MDU5NjIsImV4cCI6MTcyMjU0MTk2Mn0.fXwBmp7CZW4iMREaXNdii1q8SdMzaRtUzEmiQGR2uo8

###

GET http://localhost:3001/player/5

###

POST http://localhost:3001/player
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikxlb25hcmRvIiwidXNlcm5hbWUiOiJ0ZXN0ZSIsImVtYWlsIjoibGVlb25hcmRvbHV6QGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcEpBSnFKaVgwVFZOc09RRWlmbzR0dVBKenFjNFJxR3FYTDRyTGR6VFVWNnFtVjJJekFrNzIiLCJpYXQiOjE3MjI1MDU5NjIsImV4cCI6MTcyMjU0MTk2Mn0.fXwBmp7CZW4iMREaXNdii1q8SdMzaRtUzEmiQGR2uo8

{   
    "fname": "Guilherme",
    "lname": "Arezzo",
    "age":"23", 
    "country":"Uruguai",
    "position":"CAM",
    "club":"Gremio",
    "matches":"25",
    "scored":"12",
    "assist":"3"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"teste",
    "password":"123"
}

###

POST http://localhost:3001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGUiLCJpYXQiOjE3MjIwNzI2Mjl9.miik9ks7ZNE_M_-QuPYuWcHfBDdksejnMNfuyDf6kFo"
}

###

DELETE http://localhost:3001/logout
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikxlb25hcmRvIiwidXNlcm5hbWUiOiJ0ZXN0ZSIsImVtYWlsIjoibGVlb25hcmRvbHV6QGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcEpBSnFKaVgwVFZOc09RRWlmbzR0dVBKenFjNFJxR3FYTDRyTGR6VFVWNnFtVjJJekFrNzIiLCJpYXQiOjE3MjI1MDU5NjIsImV4cCI6MTcyMjU0MTk2Mn0.fXwBmp7CZW4iMREaXNdii1q8SdMzaRtUzEmiQGR2uo8"
}