GET http://localhost:3001/players

###

GET http://localhost:3001/player/5

###

POST http://localhost:3001/player
Content-Type: application/json

{
    "fname": "Joao",
    "lname": "Arezzo",
    "age":"23", 
    "country":"Uruguai",
    "position":"CAM",
    "club":"Gremio",
    "matches":"25",
    "scored":"12",
    "assist":"3"
}

###

PUT http://localhost:3001/player/edit/4
Content-Type: application/json

{
    "fname": "Pedro",
    "lname": "Arezzo",
    "age":"23", 
    "country":"Uruguai",
    "position":"CAM",
    "club":"Gremio",
    "matches":"25",
    "scored":"12",
    "assist":"5"
}

### 

DELETE http://localhost:3001/player/edit/3


### 

POST http://localhost:3001/register
Content-Type: application/json

{
    "name":"Leonardo Luz",
    "username": "LeeoLz",
    "email": "leeonardoluz@gmail.com",
    "password": "123"
}

###

POST http://localhost:3001/login
Content-Type: application/json
{
    "username":"teste",
    "password":"123"
}

###

GET http://localhost:3001/player/edit/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGUiLCJpYXQiOjE3MjIwNzc5NjAsImV4cCI6MTcyMjA4MTU2MH0.9AMAuoq7qHX5v4uvAcMGNC0ORfJg8JqD1ptg9h1cvpw

###

POST http://localhost:3001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGUiLCJpYXQiOjE3MjIwNzI2Mjl9.miik9ks7ZNE_M_-QuPYuWcHfBDdksejnMNfuyDf6kFo"
}

###

DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGUiLCJpYXQiOjE3MjIwNzI0NTJ9.HawIV4x46bFd5RyAReR5WqiABOVvEUPIOwqNXqAMTTg"
}